version: '3.9'

services:
  php:
    build: docker/php
    volumes:
      - ./:/app
    working_dir: /app
    user: ${HOST_UID}:${HOST_GID}
    env_file:
      - .env
    tty: true

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    user: ${HOST_UID}:${HOST_GID}
    env_file:
      - .env
    entrypoint: composer